name: SageMaker Notebook Workflow

on:
  workflow_dispatch: # Manually triggered workflow
  schedule:
    - cron: "*/2 * * * *"

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH }}
          HOSTNAME: ${{ secrets.IP }}
          USER_NAME: "ec2-user"

        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          echo "Hello World"

  # start_notebook:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     # - name: Set up AWS credentials
  #     #   run: |
  #     #     echo "AWS_ACCESS_KEY_ID=${{ secrets.ID }}" >> $GITHUB_ENV
  #     #     echo "AWS_SECRET_ACCESS_KEY=${{ secrets.KEY }}" >> $GITHUB_ENV

  #     # - name: Start SageMaker Notebook Instance
  #     #   run: |
  #     #     aws sagemaker start-notebook-instance --notebook-instance-name sample --region ap-south-1
  #     #   env:
  #     #     AWS_ACCESS_KEY_ID: ${{ secrets.ID }}
  #     #     AWS_SECRET_ACCESS_KEY: ${{ secrets.KEY }}

  #     # Wait for the notebook instance to be in the 'InService' state

  # clone_and_run:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       run: |
  #         git clone https://github.com/AdityaSai2004/trigger.git
  #         cd trigger

  #     - name: Run Shell Script
  #       run: |
  #         echo "AWS_ACCESS_KEY_ID=${{ secrets.ID }}"

  #         ssh -i ${{ secrets.SSH }} ec2-user@${{ secrets.IP }} "cd /trigger && chmod +x runner.sh && ./runner.sh"
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.KEY}}

  # # Optionally, stop the notebook instance when done
  # - name: Stop SageMaker Notebook Instance
  #   run: |
  #     # Use AWS CLI or SDK to stop the SageMaker notebook instance
  #     # Example: aws sagemaker stop-notebook-instance --notebook-instance-name YourNotebookInstanceName
